"""Add BM25 full-text search table for hybrid search

Revision ID: d3fb5a9677e5
Revises: 92a0af6a0f93
Create Date: 2025-10-30 20:36:27.753757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3fb5a9677e5'
down_revision: Union[str, None] = '92a0af6a0f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bm25_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bm25_documents_collection_document', 'bm25_documents', ['collection_name', 'document_id'], unique=False)
    op.create_index('idx_bm25_documents_fts', 'bm25_documents', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_bm25_documents_collection_name'), 'bm25_documents', ['collection_name'], unique=False)
    op.create_index(op.f('ix_bm25_documents_document_id'), 'bm25_documents', ['document_id'], unique=False)

    # Create trigger function to automatically update tsvector
    op.execute("""
        CREATE OR REPLACE FUNCTION bm25_documents_content_tsv_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.content_tsv := to_tsvector('english', NEW.content);
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
    """)

    # Create trigger that calls the function
    op.execute("""
        CREATE TRIGGER bm25_documents_content_tsv_update
        BEFORE INSERT OR UPDATE OF content ON bm25_documents
        FOR EACH ROW
        EXECUTE FUNCTION bm25_documents_content_tsv_trigger();
    """)
    op.alter_column('conversations', 'use_rag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'use_scratchpad',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('documents', 'num_chunks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('knowledge_pools_collection_name_key'), 'knowledge_pools', type_='unique')
    op.drop_index(op.f('ix_knowledge_pools_collection_name'), table_name='knowledge_pools')
    op.create_index(op.f('ix_knowledge_pools_collection_name'), 'knowledge_pools', ['collection_name'], unique=True)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False),
               existing_nullable=False)
    op.alter_column('scratchpad_entries', 'entry_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('TODO', 'NOTE', 'JOURNAL', name='scratchpadentrytype', native_enum=False),
               existing_nullable=False)
    op.alter_column('scratchpad_entries', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_memories', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_memories', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_nullable=False)
    op.alter_column('scratchpad_entries', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('scratchpad_entries', 'entry_type',
               existing_type=sa.Enum('TODO', 'NOTE', 'JOURNAL', name='scratchpadentrytype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_knowledge_pools_collection_name'), table_name='knowledge_pools')
    op.create_index(op.f('ix_knowledge_pools_collection_name'), 'knowledge_pools', ['collection_name'], unique=False)
    op.create_unique_constraint(op.f('knowledge_pools_collection_name_key'), 'knowledge_pools', ['collection_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'num_chunks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus', native_enum=False),
               server_default=sa.text("'pending'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('documents', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'upload'::character varying"),
               existing_nullable=False)
    op.alter_column('conversations', 'use_scratchpad',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'use_rag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_bm25_documents_document_id'), table_name='bm25_documents')
    op.drop_index(op.f('ix_bm25_documents_collection_name'), table_name='bm25_documents')
    op.drop_index('idx_bm25_documents_fts', table_name='bm25_documents', postgresql_using='gin')
    op.drop_index('idx_bm25_documents_collection_document', table_name='bm25_documents')

    # Drop trigger and function
    op.execute("DROP TRIGGER IF EXISTS bm25_documents_content_tsv_update ON bm25_documents;")
    op.execute("DROP FUNCTION IF EXISTS bm25_documents_content_tsv_trigger();")

    op.drop_table('bm25_documents')
    # ### end Alembic commands ###
